name: Update CHANGELOG on Tag

on:
  push:
    tags:
      - 'v[0-9]+\\.[0-9]+\\.[0-9]+'

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v3

      - name: CHANGELOG aktualisieren
        # This step uses the requarks/changelog-action to update the CHANGELOG file
        # based on the latest tag. It requires a GitHub token for authentication
        # and uses the tag from the current GitHub reference.
        uses: requarks/changelog-action@v1
        with:
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          create_file: true 
          
